    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ apache_packages }}"
    - name: Start Apache server
      service:
        name: "{{ item }}"
        state: started
        enabled: True
      with_items: "{{ services }}"
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/