    - name: Install Apache packages
      yum:
        name: "{{ apache_packages }}"
        state: present      
    - name: Start Apache server
      service:
        name: "{{ services }}"
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/