---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: 
          - httpd
          - git
          - wget
          - vim
          - curl
          - htop
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
